enableGlobalCache: false

enableTelemetry: false

injectEnvironmentFiles:
  - .env.yarn?
  - .env.yarn.local?

nodeLinker: node-modules

packageExtensions:
  "@graphql-codegen/plugin-helpers@*":
    dependencies:
      "@graphql-tools/apollo-engine-loader": "*"
  "@inquirer/core@^10.0.0":
    dependencies:
      "@types/node": "*"
  "@types/react-dom@*":
    dependencies:
      react: "*"
  "@types/react@*":
    dependencies:
      prop-types: "*"
      scheduler: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  eslint-config-next@*:
    peerDependencies:
      "@eslint/eslintrc": "*"
      next: "*"
      react: "*"
      react-dom: "*"
  node-fetch@*:
    dependencies:
      encoding: "*"

pnpMode: strict

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.10.3.cjs
